package com.example.driveswipe

object ServiceContract {
    const val EXTRA_NIGHT_MODE = "NIGHT_MODE"
    const val EXTRA_ACTION_COOLDOWN_MS = "ACTION_COOLDOWN_MS"
    const val EXTRA_VOLUME_TICK_MS = "VOLUME_TICK_MS"
    const val EXTRA_PINCH_THRESHOLD = "PINCH_THRESHOLD"
    const val EXTRA_PINCH_RELEASE_THRESHOLD = "PINCH_RELEASE_THRESHOLD"
    const val EXTRA_SWIPE_THRESHOLD = "SWIPE_THRESHOLD"
    const val EXTRA_SWIPE_TIMEOUT_MS = "SWIPE_TIMEOUT_MS"
    const val EXTRA_ALERTING_BURST_MS = "ALERTING_BURST_MS"
    const val EXTRA_ACTIVE_TIMEOUT_MS = "ACTIVE_TIMEOUT_MS"
    const val EXTRA_IDLE_INFERENCE_INTERVAL_MS = "IDLE_INFERENCE_INTERVAL_MS"
    const val EXTRA_MAP_PINCH_RIGHT = "MAP_PINCH_RIGHT"
    const val EXTRA_MAP_PINCH_LEFT = "MAP_PINCH_LEFT"
    const val EXTRA_MAP_TWO_FINGER = "MAP_TWO_FINGER"
    const val EXTRA_MAP_VOLUME_UP = "MAP_VOLUME_UP"
    const val EXTRA_MAP_VOLUME_DOWN = "MAP_VOLUME_DOWN"
    const val EXTRA_HUD_DURATION_MS = "HUD_DURATION_MS"

    const val ACTION_GESTURE_EVENT = "com.example.driveswipe.ACTION_GESTURE_EVENT"
    const val ACTION_ENGINE_STATE_EVENT = "com.example.driveswipe.ACTION_ENGINE_STATE_EVENT"
    const val ACTION_ROUTINE_START = "com.example.driveswipe.action.ROUTINE_START"
    const val ACTION_ROUTINE_STOP = "com.example.driveswipe.action.ROUTINE_STOP"
    const val EXTRA_EVENT_GESTURE = "EVENT_GESTURE"
    const val EXTRA_EVENT_ACTION = "EVENT_ACTION"
    const val EXTRA_ENGINE_STATE = "ENGINE_STATE"
}
